# Generated by Django 5.1.3 on 2024-11-26 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercrud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
