# Generated by Django 5.1.3 on 2024-11-27 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercrud', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user_doc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usercrud.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='doc_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user_doc'], name='usercrud_lo_user_do_67239d_idx'),
        ),
    ]
