# Generated by Django 5.1.3 on 2024-11-27 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercrud', '0006_log_user_doc_alter_log_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usercrud.userprofile'),
        ),
    ]
